// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3F4Mtj74GWuzE7UTw_4KtqNomya9IgXY',
    appId: '1:532657393843:web:eb74566a8a70601eb020c6',
    messagingSenderId: '532657393843',
    projectId: 'chatapps-b8374',
    authDomain: 'chatapps-b8374.firebaseapp.com',
    storageBucket: 'chatapps-b8374.appspot.com',
    measurementId: 'G-M9D6N2W13R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5WTdVb_Z3N8RkWMk9yz30L7FdoEr60wg',
    appId: '1:532657393843:android:7ddb36bf43abe267b020c6',
    messagingSenderId: '532657393843',
    projectId: 'chatapps-b8374',
    storageBucket: 'chatapps-b8374.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzNMS_eMJZCOn7X5mSpbLcfQ45dLrGRrM',
    appId: '1:532657393843:ios:0292740d1f0075c3b020c6',
    messagingSenderId: '532657393843',
    projectId: 'chatapps-b8374',
    storageBucket: 'chatapps-b8374.appspot.com',
    iosBundleId: 'com.fernosha.simplechatapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzNMS_eMJZCOn7X5mSpbLcfQ45dLrGRrM',
    appId: '1:532657393843:ios:90245a79bba1e17db020c6',
    messagingSenderId: '532657393843',
    projectId: 'chatapps-b8374',
    storageBucket: 'chatapps-b8374.appspot.com',
    iosBundleId: 'com.fernosha.simplechatapps.RunnerTests',
  );
}
